BEGIN CMGMIRIJ


I_C_T AERIEJ 4 QuayleDeadComment
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN @0
=
@1
END

I_C_T AERIEJ 5 QuayleDeadComment
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN @0
=
@1
END

I_C_T AERIEJ 6 QuayleDeadComment
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN @0
=
@1
END

I_C_T2 ANOMENJ 104 MiriamAnomenHostile
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@2
= @3
== ANOMENJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@4 DO ~LeaveParty()
Enemy()~
END

I_C_T ARAN 18 FiveFlagonDefectors
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@5
END

I_C_T BODHI 12 MiriamBodhi1
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@6
END

I_C_T BODHI 13 MiriamBodhi2
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@7
END

I_C_T BODHI 26 MiriamBodhi3
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@8
END

I_C_T CERND 70 MiriamCernd1
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@9
END

I_C_T COPGREET 1 MiriamFrankie
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
 @10
END

I_C_T EDWIN 3 MiriamEdwin1
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@11
END

I_C_T EDWIN 10 MiriamEdwin2
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@12
== EDWIN IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@13 DO ~SetGlobal("EdwinTold","GLOBAL",1)
Enemy()~
END

I_C_T EDWINJ 10 MiriamEdwinaNether
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@14
== EDWIN IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@15
END

I_C_T FIRAMB01 2 MiriamWindspearWerewolf
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
 @16
== FIRAMB01
 @17
END

I_C_T2 HAEGAN 1 MiriamHaegan
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@18
END

I_C_T HELLJON 7 MiriamHellFight
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN @19
END

I_C_T HELLJON 8 MiriamHellFight
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN @19
END

I_C_T HELLJON 9 MiriamHellFight
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN @19
END

I_C_T HELLJON 10 MiriamHellFight
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN @19
END

I_C_T HENDAK 17 MiriamHendak
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
 @20
END

I_C_T IMOEN2 22 MiriamLeaveImoen
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@21
END

I_C_T ISAEA 28 MiriamNaliaKidnap
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@22
=
@23
END

I_C_T JAHEIRAJ 54 MiriamJaheira1
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@24
== JAHEIRAJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@25
END

I_C_T KORGANJ 34 MiriamKorganTomb
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@26
== KORGANJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@27
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@28
== KORGANJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@29
END

I_C_T LEHTIN 10 MiriamLehtin
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@30
END

I_C_T MAEVAR 7 MiriamMaevarComment
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@31
=
@32
END

I_C_T MAEVAR 8 MiriamMaevarComment
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@31
=
@32
END

I_C_T MAEVAR 9 MiriamMaevarComment
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@31
=
@32
END

I_C_T MAEVAR 17 MiriamMaevarSteal1
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@33
END

I_C_T MAEVAR 16 MiriamMaevarSteal2
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@34
END

I_C_T MAEVAR 31 MiriamMaevarTraitor
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@35
END

I_C_T MAZZYJ 115 MiriamMazzyPoison
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@36
END

I_C_T PIRCOR03 0 MiriamMaleEscort1
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@37
END

I_C_T PIRCOR03 1 MiriamMaleEscort2
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@37
END

I_C_T PIRCOR03 2 MiriamMaleEscort3
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@37
END

I_C_T PLAYER1 16 MiriamIrenicusDead
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN @38
END

I_C_T PLAYER1 25 MiriamInHell
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN @39
=
@40
END

I_C_T PPAPHRIL 0 MiriamAphril
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@41
END

I_C_T PPAPHRIL 4 MiriamAphril
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@42
END

I_C_T PPAPHRIL 8 MiriamAphril
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@43
END

I_C_T PPIRENI1 4 MiriamPPIreni1
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@44
END

I_C_T PPIRENI1 16 MiriamPPIreni2
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@45
END

I_C_T PPIRENI1 22 MiriamPPIreni3
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@46
END

I_C_T PPIRENI2 32 MiriamSpellholdFight
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@47
END

I_C_T PPSAEM 59 SaemonBetraMiriam
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@48
END

I_C_T PPSAEM2 4 SaemonSpellhold
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@49
== PPSAEM2 IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@50
END

I_C_T PPSAEM2 19 SaemonSpellhold2
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@51
END

I_C_T RAELIS 79 RaelisBountyBribe
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@52
END

I_C_T RENAL 18 MiriamRenal1
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@53
== RENAL IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@54
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@55
== RENAL IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@56
END

I_C_T RENAL 22 MiriamRenal2
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@57
END

I_C_T RENAL 47 MiriamRenal3
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@58
END

I_C_T RENAL 69 MiriamRenal4
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@59
END

I_C_T SAHKNG01 36 MiriamSahkng
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@60
END

I_C_T SURLY 17 MiriamSurly
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@61
== AERIEJ IF ~IsValidForPartyDialog("Aerie") IsValidForPartyDialog("cmgmiriam")~ THEN
@62
END

I_C_T TOLGER 18 MiriamTolger1
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@63
END

I_C_T TOLGER 76 MiriamTolger2
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@64
END

I_C_T THIEF1 5 MiriamThief1
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@65
END

I_C_T THIEF2 6 MiriamThief2
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@66
END

I_C_T THIEF3 0 Miriamthief3
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@67
END

I_C_T THIEF3 1 Miriamthief3a
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@68
END

I_C_T THIEF4 1 Miriamthief4
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@69
END

I_C_T THIEF4 4 Miriamthief42
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@70
END

I_C_T THIEF6 6 MiriamZyntris
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@71
END

I_C_T THIEF8 2 Miriamthief8
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@72
END

I_C_T UDDEMON 8 MiriamGiveDemonEggs
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@73
== UDDEMON @74
END

I_C_T UDPHAE01 61 MiriamPhaere1
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN 
@75
END

I_C_T UDPHAE01 151 MiriamDeceivePhaere
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@76
END

I_C_T UDSILVER 9 MiriamDragonComment1
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@77
END

I_C_T UDSILVER 18 MiriamDragonComment2
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@78
END

I_C_T UDSILVER 49 MiriamDragonComment2
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@79
END

I_C_T UDSOLA01 117 MiriamKillSola
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@80
==UDSOLA01 @81
END

I_C_T UDSVIR03 6 MiriamEarthquakeQuestComment1
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@82
END

I_C_T UDSVIR03 27 MiriamEarthquakeQuestComment2
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@83
END

I_C_T UDSVIR04 5 MiriamThreat
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@84
END

I_C_T VICONI 2 MiriamViconiaJoin
== CMGMIRIJ   IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
  @85
  =
  @86
END

I_C_T YOSHJ 113 MiriamYoshBetrayal
== CMGMIRIJ IF ~IsValidForPartyDialog("cmgmiriam")~ THEN
@87
END

I_C_T YUSUF 2 MiriamYusuf
== CMGMIRIJ IF ~InParty("cmgmiriam")~ THEN
@88
END

EXTEND_BOTTOM PLAYER1 33
IF ~IsValidForPartyDialog("cmgmiriam")
Global("CMGMiriamDidTOLThing","GLOBAL",0)~ THEN DO ~SetGlobal("CMGMiriamDidTOLThing","GLOBAL",1)~ GOTO P133Miriam
END

APPEND PLAYER1
IF ~~ P133Miriam
SAY @89
++ @90 EXTERN CMGMIRIJ doordie
++ @91 EXTERN CMGMIRIJ bowout
++ @92 EXTERN CMGMIRIJ thankyou
END
END

APPEND CMGMIRIJ
IF ~~ doordie
SAY @93
IF ~~ GOTO tolend
END

IF ~~ tolend
SAY @94
COPY_TRANS PLAYER1 33
END

IF ~~ bowout
SAY @95
IF ~~ GOTO tolend
END

IF ~~ thankyou
SAY @96
IF ~~ GOTO tolend
END
END

CHAIN IF WEIGHT #-1 
~InParty("cmgmiriam")
See("cmgmiriam")
!StateCheck("cmgmiriam",STATE_SLEEPING)
Global("DRMiriamSal","LOCALS",0)~ THEN SALVANAS MiriamSalvanas
@97
=
@98
DO ~SetGlobal("DRMiriamSal","LOCALS",1)~
== CMGMIRIJ @99
== SALVANAS @100
== CMGMIRIJ @101
== SALVANAS @102
== CMGMIRIJ @103
== SALVANAS @104
== CMGMIRIJ @105
== SALVANAS @106
== CMGMIRIJ @107
EXIT


CHAIN IF WEIGHT #-1 
~InParty("cmgmiriam")
InMyArea("cmgmiriam")
!StateCheck("cmgmiriam",STATE_SLEEPING)
Global("cmgmiriamslkid3","LOCALS",0)~ THEN URCHIN2 cmgmiriamurch2
@108
DO ~SetGlobal("cmgmiriamslkid3","LOCALS",1)~
== CMGMIRIJ @109
== URCHIN2 @110
EXIT



CHAIN  IF WEIGHT #-1 
~InParty("cmgmiriam")
InMyArea("cmgmiriam")
!StateCheck("cmgmiriam",STATE_SLEEPING)
Global("cmgmiriamslkid2","LOCALS",0)~ THEN URCHIN1 cmgmiriamurch1
@111
DO ~SetGlobal("cmgmiriamslkid2","LOCALS",1)~
== CMGMIRIJ @112
EXIT



CHAIN IF WEIGHT #-1 
~InParty("cmgmiriam")
InMyArea("cmgmiriam")
!StateCheck("cmgmiriam",STATE_SLEEPING)
Global("cmgmiriamslkid1","LOCALS",0)~ THEN URCHIN3 cmgmiriamurch3
@113
DO ~SetGlobal("cmgmiriamslkid1","LOCALS",1)~
== CMGMIRIJ @114
== URCHIN3 @115
== CMGMIRIJ @116
EXIT

CHAIN IF WEIGHT #-1 ~InParty("cmgmiriam")
InMyArea("cmgmiriam")
Global("cmgmiriamdruffone","LOCALS",0)~ THEN DRUFF1 cmgmiriam1
@117 DO ~SetGlobal("cmgmiriamdruffone","LOCALS",1)~
== CMGMIRIJ @118
== DRUFF1 @119
EXIT

CHAIN IF WEIGHT #-1 ~InParty("cmgmiriam")
InMyArea("cmgmiriam")
Global("cmgmiriamdrufftwo","LOCALS",0)~ THEN DRUFF2 cmgmiriam2
@120 DO ~SetGlobal("cmgmiriamdrufftwo","LOCALS",1)~
== CMGMIRIJ @121
EXIT


